# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (animal activity)
target: label

pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

encoder_name: label_encoder
encoder_save_file: label_encoder_v


features:
  - pos_x
  - pos_y
  - pos_z
  - temp
 

# train/test split
test_size: 0.1
n_splits: 5
shuffle: True

# to set the random seed
random_state: 0


# xgboost model params
max_depth: 5 
learning_rate: 0.1
n_estimators: 100
verbosity: 1
objective: "multi:softmax"
use_label_encoder: False
eval_metric: "mlogloss"


